# 공통 설정
mode: time_reference  #date_range 또는 time_points far_time_process
target: Livinglab  # 또는 Livinglab

projection :
    {"link_id": 1,
    "speed": 1,
    "insert_time": 1,
    "_id": 0}  # ID 필요 없음.
# Model data interesting points 설정
interval: 5 # 시간 간격 (분 단위)
interest : [-12, -288, -2016]

# train, val, test 설정
train_ratio: [0.8, 0 , 0.2]  # train, val, test 비율 # val은 사용하지 않음

# 데이터 전처리 옵션
exclude_missing_links: true  # true: 비존재하는 링크 제외 (기존 모델 호환), false: max_speed로 채움 (새로운 방식)


# [mode = date_range]의 경우
date_range:
  start: "2024-05-07"
  end: "2024-05-07"
  
# [mode = time_points]의 경우
time_reference:
  date: "2024-05-08"
  time: "22:55"

# for far_time_process
far_time_process:
  start: None  # None으로 설정하면 현재 날짜로 대체됨
  end: None  # None으로 설정하면 현재 날짜로 대체됨
  interest: [-2,-3,-7,-14,-21]
  pg_projection:
    {"link_id": 1, #Link ID
     "avg_speed": 0, # ?
     "data": 1 ,  # True data
    "reg_date": 0, # 등록일
     }
  explode_list: 
    - "insert_time"  # 시간
    - "speed"  # 속도
    - "pty"  # 강수 형태 # 0: 없음, 1: 비, 2: 눈-비, 3: 눈
    - "rn1"  # 강우량
    
Postgres_info:
  host: "192.168.0.22"
  port: 5432
  database: "traffic_dev"
  user: "traffic_dev"
  password: "1234"


