environment:
  GPUSet: RTX

data:
  in_len: 36
  differ_len: 12
  out_len: 12
  batch_size: 32

param:
  gcn_true: True #whether to add graph convolution layer
  buildA_true: True #whether to construct adaptive adjacency matrix
  load_static_feature: False #whether to load static feature
  cl: False #whether to do curriculum learning
  gcn_depth: 2 #graph convolution Depth
  subgraph_size: 20 # 한번에 계산할 맵의 크기 #기본값 20
  node_dim: 40 #한번에 볼 수 있는 node의 개수
  dropout: 0.2 #dropout rate
  dilation_exponential: 1 #dilation exponential
  conv_channels: 32 #convolution channels #기본값 32
  residual_channels: 32 #residual channels
  skip_channels: 64 #skip channels
  end_channels: 128 #end channels
  in_dim: 1 #input 요소 차원의 개수 #기본값: 1
  layers: 3 #layers: 모델 깊이이 # 기본값: 3
  learning_rate: 0.001 #learning rate
  weight_decay: 0.0001 #weight decay rate
  clip: 5 #clip
  step_size1: 200 #step size
  step_size2: 100 #step size
  epochs: 200 #epochs
  early_drop: 20 #early drop threshold
  seed: 101 #random seed
  propalpha: 0.05 #propo alpha
  tanhalpha: 3 #adj alpha
  num_split: 1 #num of splits for graphs
  differSize: 1 #최근 얼마만큼을 반영할 것이니?

print:
  print_every: 200